name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Type-check
        run: deno check **/*.ts

      - name: Run unit tests
        run: deno task test:unit

      - name: Run integration tests
        run: deno task test:integration

      - name: Run E2E tests (with server)
        run: |
          # Start the server in background
          deno task start &
          SERVER_PID=$!

          # Wait for server to start
          sleep 5

          # Run E2E tests
          deno task test:e2e

          # Stop the server
          kill $SERVER_PID || true

      - name: Run benchmarks
        run: deno task bench

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Generate coverage report
        run: |
          # Run tests with coverage
          deno test --allow-all --unstable-worker-options --coverage=cov_profile tests/

          # Generate coverage report
          deno coverage cov_profile --lcov --output=coverage.lcov

          # Generate summary
          echo "## Code Coverage Summary" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          deno coverage cov_profile | tee coverage_summary.txt
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.lcov
          flags: unittests
          name: codecov-umbrella
